# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(max_length=30)),
                ('member2', models.CharField(max_length=30)),
                ('member3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.team'),
        ),
    ]
