# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participants',
            new_name='participant',
        ),
    ]
